### ISSUE TITLE
Time-based Joins Example?

### ISSUE THREAD

**Issue by charliec443** [oom-ai/oomstore#978] opened 2022-01-15 19:27 UTC
## Summary

I'm very curious about this project and am wondering if the following usecase is implemented yet as I couldn't get it working from the quickstart docs:

```console
$ oomcli import --input-file account0.csv --group account ... # contains information on day 0
$ oomcli import --input-file account1.csv --group account ... # contains information on day 1
$ oomcli import --input-file account3.csv --group account ... # contains information on day 3
```

In the `account.csv` provided in the docs, there is no event timestamp or created timestamp, so when you run `omcli join` it only takes information provided in `account3.csv`, irrespective of the event timestamp field provided.

On a related note, in a similar way after running `oomcli sync`, then `oomcli get online` only takes the very last imported file, although not a massive deal it would be "nice" QoL change if there is an option to propagate the previous revisions subject to TTL considerations (obviously not trivial).

This is a very interest library and approach to feature stores, and I wish the team best of luck!

**Comment by YikSanChan** [comment] 2022-01-16 01:56
@charliec443 First of all, welcome to our OOM land 🥳 We are glad to have you here!

> This is a very interest library and approach to feature stores, and I wish the team best of luck!

Can't thank you enough! This is very encouraging to us :) BTW, do you mind [joining our slack community](https://oom.ai/slack)? I am looking forward to building a long term connection with you and your use case :)

---

Regarding your questions on `import+join` and `sync+get`:

## `import+join`

> In the account.csv provided in the docs, there is no event timestamp or created timestamp ...

When running `import`, the timestamp of a "revision" is not given in the imported data file itself, instead, there are 2 sources:
- `oomcli import` marks these data with timestamp t=(when `import` is run)
- `oomcli import --revision <user specified timestamp>` marks these data with timestamp t=(user-specified timestamp)

> so when you run omcli join it only takes information provided in account3.csv, irrespective of the event timestamp field provided.

When you run `oomcli join`, the joined result depends on the timestamps given in the label dataset (see label.csv) as well as the revision timestamp. For example, your label.csv contains a label with timestamp=day2, then that label should be able to join with data provided in account1.csv

## `sync+get`

> oomcli get online only takes the very last imported file

This is by design, since what people need for online serving are usually the latest feature values. Being able to read slightly outdated data - could you please explain when is that useful, and we are happy to learn!

**Comment by YikSanChan** [comment] 2022-01-25 07:24
@charliec443 Gonna close the issue, feel free to reopen or create a new one for any further questions.

**Closed by YikSanChan** 2022-01-25 07:24 UTC
